baseURL = '/'
canonifyURLs=false
languageCode = 'en-us'
title = 'Microsoft NL Partner Tech Hub'
enableEmoji = true
# Change the default theme to be use when building the site with Hugo
theme = "relearn"
uglyurls = false
# settings specific to this theme's features; choose to your likings and
# consult this documentation for explanation
[params]
  # editURL = "//microsoft.github.io/NetherlandsTechPartnersHub/"
  fullURL = "//microsoft.github.io/NetherlandsTechPartnersHub/"
  description = "Tech documentation for Partners"
  author = "Microsoft NL Techteam"
  showVisitedLinks = false
  collapsibleMenu = true
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = false
  titleSeparator = "::"
  themeVariant =  ["microsoft-light"]#,"relearn-dark","relearn-light" ] # [ "relearn-light", "relearn-dark", "learn", "neon", "blue", "green", "red" ]
  disableSeoHiddenPages = true
  # this is for the stylesheet generator to allow for interactivity in mermaid
  # graphs; you usually will not need it and you should remove this for
  # security reasons
  mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
  additionalContentLanguage = [ "en" ]

[outputs]
  # add JSON to the home to support lunr search; This is a mandatory setting
  # for the search functionality
  # add PRINT to home, section and page to activate the feature to print whole
  # chapters
  home = ["HTML", "RSS",  "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML", "RSS"]

# English is the default language
defaultContentLanguage = "en"

# Here we enumerate all languages that will be used within the website
[languages]
[languages.en]
title = "Microsoft Partner Tech Hub"
weight = 1
languageName = "English"

[languages.nl]
title = "Microsoft Partner Tech Hub (Dutch)"
weight = 2
languageName = "Dutch"

[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
